# Generated by Django 2.1.7 on 2019-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='prospecto_qstion_trabaja',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=5, verbose_name='Trabaja Actualmente'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='prospecto_estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorsiado', 'Divorsiado'), ('Union Libre', 'Union Libre')], max_length=15, verbose_name='Estado Civil'),
        ),
    ]
