# Generated by Django 2.1.7 on 2019-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_auto_20190226_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='prospecto_cedula_carrera',
            field=models.CharField(max_length=50, verbose_name='Carrera '),
        ),
    ]
